cd deps
make jemalloc
cd jemalloc
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/arena.sym.o src/arena.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/background_thread.sym.o src/background_thread.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/base.sym.o src/base.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/bin.sym.o src/bin.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/bitmap.sym.o src/bitmap.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/ckh.sym.o src/ckh.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/ctl.sym.o src/ctl.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/div.sym.o src/div.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/extent.sym.o src/extent.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/extent_dss.sym.o src/extent_dss.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/extent_mmap.sym.o src/extent_mmap.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/hash.sym.o src/hash.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/hooks.sym.o src/hooks.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/large.sym.o src/large.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/log.sym.o src/log.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/malloc_io.sym.o src/malloc_io.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/mutex.sym.o src/mutex.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/mutex_pool.sym.o src/mutex_pool.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/nstime.sym.o src/nstime.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/pages.sym.o src/pages.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/prng.sym.o src/prng.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/prof.sym.o src/prof.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/rtree.sym.o src/rtree.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/stats.sym.o src/stats.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/sz.sym.o src/sz.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/tcache.sym.o src/tcache.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/ticker.sym.o src/ticker.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/tsd.sym.o src/tsd.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -emit-llvm -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/witness.sym.o src/witness.c
/bin/sh include/jemalloc/internal/private_namespace.sh src/jemalloc.sym src/arena.sym src/background_thread.sym src/base.sym src/bin.sym src/bitmap.sym src/ckh.sym src/ctl.sym src/div.sym src/extent.sym src/extent_dss.sym src/extent_mmap.sym src/hash.sym src/hooks.sym src/large.sym src/log.sym src/malloc_io.sym src/mutex.sym src/mutex_pool.sym src/nstime.sym src/pages.sym src/prng.sym src/prof.sym src/rtree.sym src/stats.sym src/sz.sym src/tcache.sym src/ticker.sym src/tsd.sym src/witness.sym > include/jemalloc/internal/private_namespace.gen.h
cp include/jemalloc/internal/private_namespace.gen.h include/jemalloc/internal/private_namespace.gen.h
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/jemalloc.o src/jemalloc.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/arena.o src/arena.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/background_thread.o src/background_thread.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/base.o src/base.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/bin.o src/bin.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/bitmap.o src/bitmap.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/ckh.o src/ckh.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/ctl.o src/ctl.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/div.o src/div.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/extent.o src/extent.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/extent_dss.o src/extent_dss.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/extent_mmap.o src/extent_mmap.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/hash.o src/hash.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/hooks.o src/hooks.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/large.o src/large.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/log.o src/log.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/malloc_io.o src/malloc_io.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/mutex.o src/mutex.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/mutex_pool.o src/mutex_pool.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/nstime.o src/nstime.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/pages.o src/pages.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/prng.o src/prng.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/prof.o src/prof.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/rtree.o src/rtree.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/stats.o src/stats.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/sz.o src/sz.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/tcache.o src/tcache.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/ticker.o src/ticker.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/tsd.o src/tsd.c
clang -std=gnu11 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/witness.o src/witness.c
clang -Wall -g3 -fvisibility=hidden -O3 -c -D_GNU_SOURCE -D_REENTRANT -emit-llvm -Iinclude -Iinclude -o src/jemalloc_cpp.o src/jemalloc_cpp.cpp
llvm-link -o lib/libjemalloc.a src/jemalloc.o src/arena.o src/background_thread.o src/base.o src/bin.o src/bitmap.o src/ckh.o src/ctl.o src/div.o src/extent.o src/extent_dss.o src/extent_mmap.o src/hash.o src/hooks.o src/large.o src/log.o src/malloc_io.o src/mutex.o src/mutex_pool.o src/nstime.o src/pages.o src/prng.o src/prof.o src/rtree.o src/stats.o src/sz.o src/tcache.o src/ticker.o src/tsd.o src/witness.o src/jemalloc_cpp.o
pwd
cd ../lua/src
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lapi.o lapi.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lcode.o lcode.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o ldebug.o ldebug.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o ldo.o ldo.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o ldump.o ldump.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lfunc.o lfunc.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lgc.o lgc.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o llex.o llex.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lmem.o lmem.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lobject.o lobject.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lopcodes.o lopcodes.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lparser.o lparser.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm  -c -o lstate.o lstate.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lstring.o lstring.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o ltable.o ltable.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o ltm.o ltm.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lundump.o lundump.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lvm.o lvm.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lzio.o lzio.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o strbuf.o strbuf.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o fpconv.o fpconv.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lauxlib.o lauxlib.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lbaselib.o lbaselib.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o ldblib.o ldblib.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o liolib.o liolib.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lmathlib.o lmathlib.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o loslib.o loslib.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o ltablib.o ltablib.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lstrlib.o lstrlib.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o loadlib.o loadlib.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o linit.o linit.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lua_cjson.o lua_cjson.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lua_struct.o lua_struct.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lua_cmsgpack.o lua_cmsgpack.c
clang -O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -emit-llvm   -c -o lua_bit.o lua_bit.c
llvm-link -o liblua.a lapi.o lcode.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o strbuf.o fpconv.o lauxlib.o lbaselib.o ldblib.o liolib.o lmathlib.o loslib.o ltablib.o lstrlib.o loadlib.o linit.o lua_cjson.o lua_struct.o lua_cmsgpack.o lua_bit.o
cd ../../hdr_histogram
clang  -emit-llvm -Wall -Os -g  -c -o hdr_histogram.o hdr_histogram.c
cd ../hiredis
clang -std=gnu11 -pedantic -c -O3 -fPIC   -Wall -W -emit-llvm -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb alloc.c
clang -std=gnu11 -pedantic -c -O3 -fPIC   -Wall -W -emit-llvm -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb net.c
clang -std=gnu11 -pedantic -c -O3 -fPIC   -Wall -W -emit-llvm -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb hiredis.c
clang -std=gnu11 -pedantic -c -O3 -fPIC   -Wall -W -emit-llvm -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb sds.c
clang -std=gnu11 -pedantic -c -O3 -fPIC   -Wall -W -emit-llvm -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb async.c
clang -std=gnu11 -pedantic -c -O3 -fPIC   -Wall -W -emit-llvm -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb read.c
clang -std=gnu11 -pedantic -c -O3 -fPIC   -Wall -W -emit-llvm -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb sockcompat.c
llvm-link -o libhiredis.a alloc.bc net.bc hiredis.bc sds.bc async.bc read.bc sockcompat.bc
cd ../linenoise
clang -emit-llvm -Wall -Os -g -o linenoise.o -c linenoise.c
cd ../../src 
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o quicklist.o -c quicklist.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o adlist.o -c adlist.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o ae.o -c ae.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o anet.o -c anet.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o dict.o -c dict.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o server.o -c server.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o sds.o -c sds.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o zmalloc.o -c zmalloc.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o lzf_c.o -c lzf_c.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o lzf_d.o -c lzf_d.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o pqsort.o -c pqsort.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o zipmap.o -c zipmap.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o sha1.o -c sha1.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o ziplist.o -c ziplist.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o release.o -c release.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o networking.o -c networking.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o util.o -c util.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o object.o -c object.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o db.o -c db.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o replication.o -c replication.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o rdb.o -c rdb.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o t_string.o -c t_string.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o t_list.o -c t_list.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o t_set.o -c t_set.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o t_zset.o -c t_zset.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o t_hash.o -c t_hash.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o config.o -c config.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o aof.o -c aof.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o pubsub.o -c pubsub.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o multi.o -c multi.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o debug.o -c debug.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o sort.o -c sort.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o intset.o -c intset.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o syncio.o -c syncio.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o cluster.o -c cluster.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o crc16.o -c crc16.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o endianconv.o -c endianconv.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o slowlog.o -c slowlog.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o scripting.o -c scripting.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o bio.o -c bio.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o rio.o -c rio.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o rand.o -c rand.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o memtest.o -c memtest.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o crcspeed.o -c crcspeed.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o crc64.o -c crc64.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o bitops.o -c bitops.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o sentinel.o -c sentinel.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o notify.o -c notify.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o setproctitle.o -c setproctitle.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o blocked.o -c blocked.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o hyperloglog.o -c hyperloglog.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o latency.o -c latency.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o sparkline.o -c sparkline.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o redis-check-rdb.o -c redis-check-rdb.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o redis-check-aof.o -c redis-check-aof.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o geo.o -c geo.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o lazyfree.o -c lazyfree.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o module.o -c module.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o evict.o -c evict.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o expire.o -c expire.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o geohash.o -c geohash.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o geohash_helper.o -c geohash_helper.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o childinfo.o -c childinfo.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o defrag.o -c defrag.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o siphash.o -c siphash.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o rax.o -c rax.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o t_stream.o -c t_stream.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o listpack.o -c listpack.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o localtime.o -c localtime.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o lolwut.o -c lolwut.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o lolwut5.o -c lolwut5.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o lolwut6.o -c lolwut6.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o acl.o -c acl.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o tracking.o -c tracking.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o connection.o -c connection.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o tls.o -c tls.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o sha256.o -c sha256.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o timeout.o -c timeout.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o setcpuaffinity.o -c setcpuaffinity.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o monotonic.o -c monotonic.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o mt19937-64.o -c mt19937-64.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o resp_parser.o -c resp_parser.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o call_reply.o -c call_reply.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o redis-benchmark.o -c redis-benchmark.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o redis-cli.o -c redis-cli.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o redisassert.o -c redisassert.c
clang -pedantic -DREDIS_STATIC= -Wno-c11-extensions -std=gnu11 -Wall -W -emit-llvm -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -DUSE_JEMALLOC -I../deps/jemalloc/include -MMD -o cli_common.o -c cli_common.c


llvm-link -o redis-server.bc adlist.o quicklist.o ae.o anet.o dict.o server.o sds.o zmalloc.o lzf_c.o lzf_d.o pqsort.o zipmap.o sha1.o ziplist.o release.o networking.o util.o object.o db.o replication.o rdb.o t_string.o t_list.o t_set.o t_zset.o t_hash.o config.o aof.o pubsub.o multi.o debug.o sort.o intset.o syncio.o cluster.o crc16.o endianconv.o slowlog.o scripting.o bio.o rio.o rand.o memtest.o crcspeed.o crc64.o bitops.o sentinel.o notify.o setproctitle.o blocked.o hyperloglog.o latency.o sparkline.o redis-check-rdb.o redis-check-aof.o geo.o lazyfree.o module.o evict.o expire.o geohash.o geohash_helper.o childinfo.o defrag.o siphash.o rax.o t_stream.o listpack.o localtime.o lolwut.o lolwut5.o lolwut6.o acl.o tracking.o connection.o tls.o sha256.o timeout.o setcpuaffinity.o monotonic.o mt19937-64.o resp_parser.o call_reply.o ../deps/hiredis/libhiredis.a ../deps/lua/src/liblua.a ../deps/jemalloc/lib/libjemalloc.a
#clang   -g -ggdb -rdynamic -o redis-server adlist.o quicklist.o ae.o anet.o dict.o server.o sds.o zmalloc.o lzf_c.o lzf_d.o pqsort.o zipmap.o sha1.o ziplist.o release.o networking.o util.o object.o db.o replication.o rdb.o t_string.o t_list.o t_set.o t_zset.o t_hash.o config.o aof.o pubsub.o multi.o debug.o sort.o intset.o syncio.o cluster.o crc16.o endianconv.o slowlog.o scripting.o bio.o rio.o rand.o memtest.o crcspeed.o crc64.o bitops.o sentinel.o notify.o setproctitle.o blocked.o hyperloglog.o latency.o sparkline.o redis-check-rdb.o redis-check-aof.o geo.o lazyfree.o module.o evict.o expire.o geohash.o geohash_helper.o childinfo.o defrag.o siphash.o rax.o t_stream.o listpack.o localtime.o lolwut.o lolwut5.o lolwut6.o acl.o tracking.o connection.o tls.o sha256.o timeout.o setcpuaffinity.o monotonic.o mt19937-64.o resp_parser.o call_reply.o ../deps/hiredis/libhiredis.a ../deps/lua/src/liblua.a ../deps/jemalloc/lib/libjemalloc.a -lm -ldl -pthread -lrt
install redis-server.bc redis-sentinel
llvm-link -o redis-cli.bc anet.o adlist.o dict.o redis-cli.o zmalloc.o release.o ae.o redisassert.o crcspeed.o crc64.o siphash.o crc16.o monotonic.o cli_common.o mt19937-64.o ../deps/hiredis/libhiredis.a ../deps/linenoise/linenoise.o ../deps/jemalloc/lib/libjemalloc.a 
llvm-link -o redis-benchmark.bc ae.o anet.o redis-benchmark.o adlist.o dict.o zmalloc.o redisassert.o release.o crcspeed.o crc64.o siphash.o crc16.o monotonic.o cli_common.o mt19937-64.o ../deps/hiredis/libhiredis.a ../deps/hdr_histogram/hdr_histogram.o ../deps/jemalloc/lib/libjemalloc.a
